// tailwind.config.js
module.exports = {
  content: [ "./index.html","./src/**/*.{html,js,vue}"],
  theme: {
    extend: {
      colors: {
        // 使用 CSS 变量，这样可以根据域名动态切换颜色
        'themeblack': 'var(--color-themeblack)',
        'themewhite': 'var(--color-themewhite)',
        'rgbawhite10': 'var(--color-rgbawhite10)',
        'rgbawhite30': 'var(--color-rgbawhite30)',
        'rgbawhite50': 'var(--color-rgbawhite50)',
        'rgbawhite80': 'var(--color-rgbawhite80)',
        'rgbablack15': 'var(--color-rgbablack15)',
        'rgbablack30': 'var(--color-rgbablack30)',
        'rgbablack50': 'var(--color-rgbablack50)',
        'rgbablack80': 'var(--color-rgbablack80)',
        'theme': 'var(--color-theme)',
        'theme-text': 'var(--color-theme-text)',
        'theme-light': 'var(--color-theme-light)',
        'themetext': 'var(--color-themetext)',
        'one': 'var(--color-one)',
        'two': 'var(--color-two)',
        'three': 'var(--color-three)',
        'four': 'var(--color-four)',
        'textcolorsix': 'var(--color-textcolorsix)',
        'nine': 'var(--color-nine)',
        'border1': 'var(--color-border1)',
        'tablebg': 'var(--color-tablebg)',
        'tablergba': 'var(--color-tablergba)',
        'tablergba40': 'var(--color-tablergba40)',
        'tablergba20': 'var(--color-tablergba20)',
        'tablergba10': 'var(--color-tablergba10)',
        'gold-100': 'var(--color-gold-100)',
        'gold-500': 'var(--color-gold-500)',
        'header-bg': 'var(--color-header-bg)',
        'aside-bg': 'var(--color-aside-bg)',
        'body-bg': 'var(--color-body-bg)',
        'default-bg': 'var(--color-default-bg)',
        'drawer-text': 'var(--color-drawer-text)',
        'loginlinear-3': 'var(--color-loginlinear-3)',
        'loginlinear-4': 'var(--color-loginlinear-4)',
        'themecardlinear1': 'var(--color-themecardlinear1)',
        'themecardlinear2': 'var(--color-themecardlinear2)',
        'redbglinear1': 'var(--color-linear-9)',
        'redbglinear2': 'var(--color-linear-10)',
        'linear-11': 'var(--color-linear-11)',
        'linear-12': 'var(--color-linear-12)',
        'linear-18': 'var(--color-linear-18)',
        'linear-19': 'var(--color-linear-19)',
        'linear-22': 'var(--color-linear-22)',
        'linear-23': 'var(--color-linear-23)',
        'text-1': 'var(--color-text-1)',
        'pwa': 'var(--color-pwa)',
        'homeranktext': 'var(--color-homeranktext)',
        'searchbg': 'var(--color-searchbg)',
        'searchborder': 'var(--color-searchborder)',
        'faqcolor1': 'var(--color-faqcolor1)',
        'faqcolor2': 'var(--color-faqcolor2)',
        'faqcolor3': 'var(--color-faqcolor3)',
        'faqcolor4': 'var(--color-faqcolor4)',
        'btnlinar1': 'var(--color-btnlinar1)',
        'btnlinar2': 'var(--color-btnlinar2)',
        'btnlinar3': 'var(--color-btnlinar3)',
        'btnlinar4': 'var(--color-btnlinar4)',
        // 模板二新加
        'noticelinear1': 'var(--color-noticelinear1)',
        'noticelinear2': 'var(--color-noticelinear2)',
        'downloadlinear1': 'var(--color-downloadlinear1)',
        'downloadlinear2': 'var(--color-downloadlinear2)',
        'downloadlinear3': 'var(--color-downloadlinear3)',
        'downloadlinear4': 'var(--color-downloadlinear4)',
        'minecardbg': 'var(--color-minecardbg)',
        'richlinar1': 'var(--color-richlinar1)',
        'richlinar2': 'var(--color-richlinar2)',
        'minelinear1': 'var(--color-minelinear1)',
        'minelinear2': 'var(--color-minelinear2)',
        'defaultborder': 'var(--color-defaultborder)',
        'morelinear1': 'var(--color-morelinear1)',
        'morelinear2': 'var(--color-morelinear2)',
        'btncolor': 'var(--color-btncolor)',
        'card1': 'var(--color-card1)',
        'card2': 'var(--color-card2)',
        'allbtn': 'var(--color-allbtn)',
        'six': 'var(--color-six)',
        'cardbg': 'var(--color-cardbg)',
        'mysteriousgoldtext': 'var(--color-mysteriousgoldtext)',
        'redpacktext': 'var(--color-redpacktext)',
        'pddcardtext': 'var(--color-pddcardtext)',
        'texterror': 'var(--color-texterror)',
        // 模板三新加
        'themetext0': 'var(--color-themetext0)',
        'themetext1': 'var(--color-themetext1)',
        'themetext2': 'var(--color-themetext2)',
        'themetext3': 'var(--color-themetext3)',
        'themetext4': 'var(--color-themetext4)',
        // 模板4新加
        'tablebg2': 'var(--color-tablebg2)',
        'activitybox1': 'var(--color-activitybox1)',
        'activitybox2': 'var(--color-activitybox2)',
        'activityborder1': 'var(--color-activityborder1)',
        'activityborder2': 'var(--color-activityborder2)',
        'm4tentext': 'var(--color-m4tentext)',
        'm4ninetext': 'var(--color-m4ninetext)',

        //模板五新加
        'inputcolor1': 'var(--color-inputcolor1)',
        'inputcolor2': 'var(--color-inputcolor2)',
        'inputborder': 'var(--color-inputborder)',
        'tablebg1': 'var(--color-tablebg1)',
        'btn1_bg': 'var(--color-btn1_bg)',
        'btn_border': 'var(--color-btn_border)',
        'thirsmodel1': 'var(--color-thirsmodel1)',
        'thirsmodel2': 'var(--color-thirsmodel2)',
        'thirsmodelboder': 'var(--color-thirsmodelboder)',
        'activitymodel1': 'var(--color-activitymodel1)',
        'activitymodel2': 'var(--color-activitymodel2)',
      },
      width: {
        'wrap': '23.4375rem',
        'half': '11.71875rem'
      },
      padding: {
        'ctx': '1rem',
      },
      margin: {
        'ctx': '1rem',
      },
      borderRadius: {
        '4xl': '2rem',
      },
    },
  },
  plugins: [],
}